vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /club/
            upload_destination: '%kernel.root_dir%/../web/club/'
            namer: vich_uploader.namer_uniqid
