#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_countries_get_item:
  path: '/api/room_r/'
  defaults:
    _controller: '\App\Controller\RoomController::index'
    _api_resource_class: 'App\Entity\Room'
    _api_item_operation_name: 'special'