<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6xxKtpu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6xxKtpu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6xxKtpu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6xxKtpu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6xxKtpu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6xxKtpu',
    'container.build_id' => 'e9567b2c',
    'container.build_time' => 1646741189,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6xxKtpu');
