<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZhDu5xN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZhDu5xN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZhDu5xN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZhDu5xN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZhDu5xN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZhDu5xN',
    'container.build_id' => 'b6b5b57d',
    'container.build_time' => 1646256844,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZhDu5xN');
