<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLxLYJTs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLxLYJTs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLxLYJTs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLxLYJTs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLxLYJTs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LxLYJTs',
    'container.build_id' => 'fc131368',
    'container.build_time' => 1646350292,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLxLYJTs');
